module Sounds exposing
    ( Image
    , Profile(..)
    , Sound
    , allProfiles
    , code
    , default
    , fromCode
    , pick
    , poster
    , title
    )

import Dict
import Random


type alias Sound =
    String


type alias Image =
    { url : String
    , alt : String
    }


type Profile
    = ClassicWeird
    | Riot
    | New
    | Kaamelott


poster : Profile -> Image
poster profile =
    { url =
        (++) "/images/sound-library/" <|
            case profile of
                ClassicWeird ->
                    "weird.webp"

                Riot ->
                    "commune.webp"

                New ->
                    "WhatsNew-1.webp"

                Kaamelott ->
                    "Kaamelott.webp"
    , alt =
        case profile of
            ClassicWeird ->
                "Photography of a man wearing a watermelon hat"

            Riot ->
                "Comic book drawing of the paris commune revolution"

            New ->
                "Stylized logo saying \"What's new\""

            Kaamelott ->
                "Kaamelott"
    }


allProfiles : List Profile
allProfiles =
    nextProfile [] |> List.reverse


nextProfile : List Profile -> List Profile
nextProfile list =
    case List.head list of
        Nothing ->
            nextProfile (ClassicWeird :: list)

        Just ClassicWeird ->
            nextProfile (Riot :: list)

        Just Riot ->
            nextProfile (New :: list)

        Just New ->
            nextProfile (Kaamelott :: list)

        Just Kaamelott ->
            list


title : Profile -> String
title profile =
    case profile of
        ClassicWeird ->
            "Classic Weird"

        Riot ->
            "Riot"

        New ->
            "New 2022/11"

        Kaamelott ->
            "Kaamelott"


code : Profile -> String
code profile =
    case profile of
        ClassicWeird ->
            "ClassicWeird"

        Riot ->
            "Riot"

        New ->
            "New2022/11"

        Kaamelott ->
            "Kaamelott"


fromCode : String -> Profile
fromCode string =
    allProfiles
        |> List.map (\profile -> ( code profile, profile ))
        |> Dict.fromList
        |> Dict.get string
        |> Maybe.withDefault ClassicWeird


default : Sound
default =
    "classic-weird/celebration.mp3"


pick : Profile -> Random.Generator Sound
pick profile =
    soundsOf profile
        |> (\( d, list ) -> Random.uniform d list)


soundsOf : Profile -> ( Sound, List Sound )
soundsOf profile =
    case profile of
        ClassicWeird ->
            ( "classic-weird/celebration.mp3"
            , classicWeird
            )

        Riot ->
            ( "riot/faut plus de gouvernement.mp3"
            , riot
            )

        New ->
            ( "classic-weird/banane.wav.mp3"
            , newSounds
            )

        Kaamelott ->
            ( "kaamelott/il_ne_comprennent_jamais_le_code.mp3"
            , kaamelottSounds
            )


newSounds : List Sound
newSounds =
    [ "classic-weird/aroundtheworld.wav.mp3"
    , "classic-weird/banane.wav.mp3"
    , "classic-weird/blablabla.wav.mp3"
    , "classic-weird/boneym_rasputin.wav.mp3"
    , "classic-weird/carldouglas_kungfufighting.wav.mp3"
    , "classic-weird/chic_freak.wav.mp3"
    , "classic-weird/coolio_ganstaparadise.wav.mp3"
    , "classic-weird/didiersuper_gensquibossent.wav.mp3"
    , "classic-weird/digitallove.wav.mp3"
    , "classic-weird/doors_strange.wav.mp3"
    , "classic-weird/drdre_stilldre.wav.mp3"
    , "classic-weird/eminem_slimshady.wav.mp3"
    , "classic-weird/indochine_aventurier.wav.mp3"
    , "classic-weird/kiss_madeforlovingyou.wav.mp3"
    , "classic-weird/lmfao_partyrockanthem.wav.mp3"
    , "classic-weird/matmatah_apologie.wav.mp3"
    , "classic-weird/mjackson_beatit.wav.mp3"
    , "classic-weird/queen_breakfree.wav.mp3"
    , "classic-weird/rickroll.wav.mp3"
    , "classic-weird/smokeonthewater.wav.mp3"
    , "classic-weird/spindoctors_twoprinces.wav.mp3"
    , "classic-weird/sweethomealabam.wav.mp3"
    , "classic-weird/thislove.wav.mp3"
    , "classic-weird/toto_africa.wav.mp3"
    , "classic-weird/toxic.wav.mp3"
    , "riot/eiffel_larue.wav.mp3"
    ]


riot : List Sound
riot =
    [ "riot/ca cest paris.mp3"
    , "riot/el pueblo unido.mp3"
    , "riot/france qui ferme sa gueule.mp3"
    , "riot/internationale.mp3"
    , "riot/internationale2.mp3"
    , "riot/milliards contre une elite.mp3"
    , "riot/mort aux patrons.mp3"
    , "riot/ravachole.mp3"
    , "riot/eiffel_larue.wav.mp3"
    ]


classicWeird : List Sound
classicWeird =
    [ "classic-weird/007-james-bond-theme.mp3"
    , "classic-weird/007-sound-final.mp3"
    , "classic-weird/a-ha-take-on-me-cut-mp3.mp3"
    , "classic-weird/anthologie-de-julien-lepers.mp3"
    , "classic-weird/aroundtheworld.wav.mp3"
    , "classic-weird/banane.wav.mp3"
    , "classic-weird/blablabla.wav.mp3"
    , "classic-weird/boneym_rasputin.wav.mp3"
    , "classic-weird/breaking-bad-intro.mp3"
    , "classic-weird/cantina-band.mp3"
    , "classic-weird/carldouglas_kungfufighting.wav.mp3"
    , "classic-weird/celebration.mp3"
    , "classic-weird/chic_freak.wav.mp3"
    , "classic-weird/complotiste.mp3"
    , "classic-weird/coolio_ganstaparadise.wav.mp3"
    , "classic-weird/denis-brogniart-ah-original.mp3"
    , "classic-weird/didiersuper_gensquibossent.wav.mp3"
    , "classic-weird/digitallove.wav.mp3"
    , "classic-weird/donald-trump-fake-news-sound-effect.mp3"
    , "classic-weird/doors_strange.wav.mp3"
    , "classic-weird/drdre_stilldre.wav.mp3"
    , "classic-weird/drwho.mp3"
    , "classic-weird/eminem_slimshady.wav.mp3"
    , "classic-weird/fake-news-great.mp3"
    , "classic-weird/flashgordontheme.mp3"
    , "classic-weird/george-micael-wham-careless-whisper-1.mp3"
    , "classic-weird/got.mp3"
    , "classic-weird/hallelujahshort.swf.mp3"
    , "classic-weird/harry-potter-hedwigs-theme-short.mp3"
    , "classic-weird/i-am-your-father_rCXrfcX.mp3"
    , "classic-weird/imperial_march.mp3"
    , "classic-weird/inceptionbutton.mp3"
    , "classic-weird/indiana-jones-theme-song.mp3"
    , "classic-weird/indochine_aventurier.wav.mp3"
    , "classic-weird/its-me-mario.mp3"
    , "classic-weird/jurrasic-theme-2-hq.mp3"
    , "classic-weird/kaamelott-theme.mp3"
    , "classic-weird/kiss_madeforlovingyou.wav.mp3"
    , "classic-weird/knight-rider.mp3"
    , "classic-weird/lemon-grab-unacceptable.mp3"
    , "classic-weird/lmfao_partyrockanthem.wav.mp3"
    , "classic-weird/macron_projet_final.mp3"
    , "classic-weird/matmatah_apologie.wav.mp3"
    , "classic-weird/mc-hammer-u-cant-touch-this.mp3"
    , "classic-weird/mission-impossible.mp3"
    , "classic-weird/mjackson_beatit.wav.mp3"
    , "classic-weird/music-missionimpossibletheme.mp3"
    , "classic-weird/nyan-cat_1.mp3"
    , "classic-weird/o-bom-o-mal-e-o-feio-velho-oeste-desafio-dont-talk-duelo-desafio-armas.mp3"
    , "classic-weird/over9000.swf.mp3"
    , "classic-weird/perlin.mp3"
    , "classic-weird/poudreperlinpinpin_fqw6cN8.mp3"
    , "classic-weird/psy-gangnam-style-1.mp3"
    , "classic-weird/queen_breakfree.wav.mp3"
    , "classic-weird/rickroll.wav.mp3"
    , "classic-weird/robin-hood-1973-whistle-stop.mp3"
    , "classic-weird/smokeonthewater.wav.mp3"
    , "classic-weird/spindoctors_twoprinces.wav.mp3"
    , "classic-weird/star-wars-john-williams-duel-of-the-fates.mp3"
    , "classic-weird/super-mario-bros-ost-8-youre-dead.mp3"
    , "classic-weird/sweethomealabam.wav.mp3"
    , "classic-weird/tetris-theme.mp3"
    , "classic-weird/the-addams-family-intro-theme-song.mp3"
    , "classic-weird/the-benny-hill-show-theme-short-sound-clip-and-quote-hark.mp3"
    , "classic-weird/the-it-crowd-theme.mp3"
    , "classic-weird/the-pink-panther-theme-song-original-version.mp3"
    , "classic-weird/the-simpsons-nelsons-haha.mp3"
    , "classic-weird/the-weather-girls-its-raining-men-1-cut-mp3.mp3"
    , "classic-weird/thislove.wav.mp3"
    , "classic-weird/toto_africa.wav.mp3"
    , "classic-weird/toxic.wav.mp3"
    , "classic-weird/untitled_3.mp3"
    , "classic-weird/utini.mp3"
    , "classic-weird/we-are-the-champions-copia.mp3"
    , "classic-weird/zelda.mp3"
    ]


kaamelottSounds : List Sound
kaamelottSounds =
    [ "kaamelott/il_ne_comprennent_jamais_le_code.mp3"

    -- kaamelott sounds autogenerated begin
    , "kaamelott/2_3_poils_de_Q.mp3"
    , "kaamelott/ah_ah_ah_les_pegus.mp3"
    , "kaamelott/ah_ah_mais_vous_etes_marteau_et_regardez_ca_ca_pisse_le_sang.mp3"
    , "kaamelott/ah_bah_alors_la_je_les_attends_les_mecs.mp3"
    , "kaamelott/ah-bah-cest-sur-on-se-marre.mp3"
    , "kaamelott/ah_bah_ouais_mais_apres_il_faut_un_peu_de_technique.mp3"
    , "kaamelott/ah-bah-voila-cherchez-pas-cest-hyper-flippant.mp3"
    , "kaamelott/ah_bravo_bah_vous_parlez_d_un_hero.mp3"
    , "kaamelott/ah-ca-quand-on-connait-pas-il-faut-se-mefier-avec-les-champignons.mp3"
    , "kaamelott/ah_cest_ca.mp3"
    , "kaamelott/ah-cest-regle-hein-je-confirme.mp3"
    , "kaamelott/ah__enfin_vous_voila_mon_ami__mais_que_se_passe_t_il_jentends_crier.mp3"
    , "kaamelott/ah_il_tape_la_ou_ca_fait_mal_hein.mp3"
    , "kaamelott/ah_le_printemps_on_crame_des_mecs.mp3"
    , "kaamelott/ah_mais_arretez_de_gueuler_comme_un_con.mp3"
    , "kaamelott/ah_nan_mais_quand_on_est_pas_habitue_c_est_drolement_impressionnant_la_magie.mp3"
    , "kaamelott/ah_non_ca_c_est_que_nous.mp3"
    , "kaamelott/ah_non_la_aujourd_hui_ca_passera_pas.mp3"
    , "kaamelott/ah-non-vous-allez-pas-bouder.mp3"
    , "kaamelott/ah_ouais_je_l_ai_fait_trop_fulgurant_la_ca_va.mp3"
    , "kaamelott/ah-ouais-vous-madressez-carrement-plus-la-parole-en-fait.mp3"
    , "kaamelott/ah_ouais_vous_seriez_une_sorte_de_bi_taupe_en_fait.mp3"
    , "kaamelott/ah_oui_bravo_une_belle_lecon_de_sport.mp3"
    , "kaamelott/ah_parce_que_c_est_la_seule_alternative_que_vous_me_proposez.mp3"
    , "kaamelott/ah-putain-ouais-en-fait-vous-mavez-fait-lever-pour-rien.mp3"
    , "kaamelott/ah_qu_est_ce_que_vous_voulez_mon_petit_bohort.mp3"
    , "kaamelott/ah_si_moi_j_irai_me_recoucher_avant_de_prendre_un_pain.mp3"
    , "kaamelott/ah-une-vache-pres-cest-pas-une-science-exacte.mp3"
    , "kaamelott/a_kadoc.mp3"
    , "kaamelott/a_la_volette1.mp3"
    , "kaamelott/allez_boire_un_coup.mp3"
    , "kaamelott/allez-bon-dieu-mais-magnez-vous-ca-pue-la-dedans.mp3"
    , "kaamelott/allez-en-garde-espece-de-petite-couille-molle.mp3"
    , "kaamelott/allez-quoi-on-a-besoin-dune-potion.mp3"
    , "kaamelott/allez_vous_preparer_mousaillon_on_largue_les_amarres_dans_une_heure.mp3"
    , "kaamelott/allez_vous_reposer_vous_l_avez_bien_merite.mp3"
    , "kaamelott/allez-y-mollo-avec-la-joie.mp3"
    , "kaamelott/allez-y-vous.mp3"
    , "kaamelott/alors__a_qui_cest_quelle_est_morte_la_va_vache.mp3"
    , "kaamelott/alors_ca_vient_ptite_bite.mp3"
    , "kaamelott/alors_des_qu_il_s_agit_d_aller_se_dorer_les_miches_en_armorique.mp3"
    , "kaamelott/alors_le_ratichon_on_a_un_ptit_creux.mp3"
    , "kaamelott/alors_moi_jai_un_petit_probleme__jai_pas_pige_un_broc_de_ce_que_vous_bavez.mp3"
    , "kaamelott/alors-oisif-obese-autant-dire-des-gros-cons.mp3"
    , "kaamelott/alors_si_j_ai_bien_resume_le_truc_vous_allez_creuser_trois_pieds_et_demi_sur_toute_la_bretagne.mp3"
    , "kaamelott/a_moi_a_lassassin.mp3"
    , "kaamelott/a_moi.mp3"
    , "kaamelott/a_mon_epoque_ca_se_faisait_pas.mp3"
    , "kaamelott/animaux_de_la_foret.mp3"
    , "kaamelott/a_plus_tard.mp3"
    , "kaamelott/apres_pour_le_detail_je_sais_pas.mp3"
    , "kaamelott/a_roulettes.mp3"
    , "kaamelott/arretez-cest-pour-deconner.mp3"
    , "kaamelott/arretez_de_parler_aux_gens.mp3"
    , "kaamelott/arretez_immediatement_de_me_prendre_pour_une_truite.mp3"
    , "kaamelott/arthour_cest_la_guerre.mp3"
    , "kaamelott/arthour.mp3"
    , "kaamelott/assiette_fromage.mp3"
    , "kaamelott/A-titre-purement-informatif.mp3"
    , "kaamelott/attendez_il_faut_que_ca_soit_vrai_tout_ce_qu_on_dit_la.mp3"
    , "kaamelott/attendez-que-je-me-suis-jamais-quoi.mp3"
    , "kaamelott/attention_attention_a_un_moment_il_y_a_des_granges_qui_vont_se_mettre_a_flamber_il_faudra_pas_demander_d_ou_sa_vient.mp3"
    , "kaamelott/au_bout_dun_moment_on_a_prefere_plus_rien_dire.mp3"
    , "kaamelott/au_bucher_demon_expie_tes_fautes.mp3"
    , "kaamelott/au_gros_sel_qu_est_ce_que_c_est_ces_conneries_vous_me_prenez_pour_une_epaule_d_agneau.mp3"
    , "kaamelott/aujourdhui_ya_du_dessert.mp3"
    , "kaamelott/ave_cesar.mp3"
    , "kaamelott/avec_sa_couille.mp3"
    , "kaamelott/avez_de_la_chance.mp3"
    , "kaamelott/a_voui_vous_avez_raison.mp3"
    , "kaamelott/bah-alors-884-charrettes-de-bouses.mp3"
    , "kaamelott/bah-ca-depend-a-partir-de-quand.mp3"
    , "kaamelott/bah_je_sais_pas_me_lacher_la_grappe_par_exemple.mp3"
    , "kaamelott/bah-on-a-pas-de-technique-mais-cest-comme-tout.mp3"
    , "kaamelott/bah_si_il_n_y_avait_que_les_oiseaux_elle_est_a_moitie_givree_de_toute_facon_on_ne_peut_pas_tout_relever_non_plus.mp3"
    , "kaamelott/bataille_de_fions.mp3"
    , "kaamelott/bateau-nage.mp3"
    , "kaamelott/ben_nous_on_a_cru_que_cetait_la_pour_faire_joli.mp3"
    , "kaamelott/ben_oui_cest_une_rime_triple__blanche_et_seche_poitrine_et_prairie_de_notre_enfance.mp3"
    , "kaamelott/bibelots-mongol-parthenon.mp3"
    , "kaamelott/bien_manger_cest_important.mp3"
    , "kaamelott/biensur-ils-ont-que-ca-a-foutre-les-paysans.mp3"
    , "kaamelott/blaireau-peignecul-tarlouze.mp3"
    , "kaamelott/bled-natal-fion.mp3"
    , "kaamelott/bohort_arreter_de_vous_vexer_sans_arret_comme_une_grosse_dinde.mp3"
    , "kaamelott/bon-alors-combien-il-faut-que-casque-pour-la-fete-aux-pecores.mp3"
    , "kaamelott/bon_bah_aller_on_demarre_et_ouvrez_les_echauguettes.mp3"
    , "kaamelott/bon_bah_ca_va_on_plaisante.mp3"
    , "kaamelott/bon_bah_je_vais_voir_ce_que_je_peux_faire.mp3"
    , "kaamelott/bon_ben_revolte.mp3"
    , "kaamelott/bon_cassez_vous.mp3"
    , "kaamelott/bon-de-toute-facon.mp3"
    , "kaamelott/bon_je_la_suis_parce_que_je_suis_tres_amoureux.mp3"
    , "kaamelott/bon_je_peux_pas_penser_a_tout_la.mp3"
    , "kaamelott/bonjour_la_pedagogie.mp3"
    , "kaamelott/bon_on_va_commencer_les_negociations.mp3"
    , "kaamelott/boule-de-feu-boule-de-feu.mp3"
    , "kaamelott/bucher1.mp3"
    , "kaamelott/bucher2.mp3"
    , "kaamelott/bucher3.mp3"
    , "kaamelott/buffet_a_vaisselle.mp3"
    , "kaamelott/burgonde_ou_anglais.mp3"
    , "kaamelott/ca-ca-doit-etre-du-code-parce-que-ca-veut-rien-dire.mp3"
    , "kaamelott/ca_change_tout.mp3"
    , "kaamelott/ca_me_fait_gerber.mp3"
    , "kaamelott/ca_me_ferait_mal.mp3"
    , "kaamelott/ca_me_plait_qu_a_moitie.mp3"
    , "kaamelott/casuffit.mp3"
    , "kaamelott/catastrophe.mp3"
    , "kaamelott/ca_va_encore_faire_des_discussions_a_rallonge.mp3"
    , "kaamelott/ca_va_j_picole_pas_souvent.mp3"
    , "kaamelott/ca_va_oui_ca_va_vous_etes_content.mp3"
    , "kaamelott/ca_va_si_faut_sonner_lalerte_vous_pouvez_bien_attendre_que_je_revienne_nan.mp3"
    , "kaamelott/ca_va_un_peu_trop_vite_pour_moi.mp3"
    , "kaamelott/ca_vous_ennuie_si_je_vomis.mp3"
    , "kaamelott/ca_vous_fait_pas_mal_a_la_tete_de_glandouiller.mp3"
    , "kaamelott/ca_vous_regarde_pas_cest_secret_ok.mp3"
    , "kaamelott/centurion_caius_camilus_lulululu.mp3"
    , "kaamelott/ce-serait-hyper.mp3"
    , "kaamelott/cest_beau_quand_meme.mp3"
    , "kaamelott/cest_bien_fait.mp3"
    , "kaamelott/cest_bien_quon_reste_un_peu_dehors.mp3"
    , "kaamelott/cest_chaud_quand_meme.mp3"
    , "kaamelott/c_est_cotelette_que_vous_comprenez_pas.mp3"
    , "kaamelott/cest_debile_cette_histoire.mp3"
    , "kaamelott/cest-de-la-daube.mp3"
    , "kaamelott/cest_de_la_merde_2.mp3"
    , "kaamelott/cest-de-la-merde-merci-messieurs.mp3"
    , "kaamelott/cest-de-la-merde.mp3"
    , "kaamelott/cest_de_la_merde.mp3"
    , "kaamelott/cest_dur.mp3"
    , "kaamelott/cest_facile_on_peut_jouer_soit_avec_des_haricots_soit_avec_des_lentilles.mp3"
    , "kaamelott/cest_honteux.mp3"
    , "kaamelott/cest_interessant.mp3"
    , "kaamelott/cest_lanniversaire_dans_tous_les_recoins.mp3"
    , "kaamelott/cest-l-autre-con-avec-ses-pinceaux.mp3"
    , "kaamelott/cest_le_genre_dendroit_ou_il_faut_parler_fort.mp3"
    , "kaamelott/cest_le_grand_qui_a_dit.mp3"
    , "kaamelott/cest_le_rendez_vous_des_glandus_la_ou_quoi.mp3"
    , "kaamelott/c-est-les-autres-qui-sont-cons.mp3"
    , "kaamelott/c_est_maintenant_quil_faut_se_secouer.mp3"
    , "kaamelott/cest-marrant-les-petits-bouts-de-fromage-par-terre.mp3"
    , "kaamelott/cest_moi_ou_il_y_a_une_ambiance_de_merde.mp3"
    , "kaamelott/C_est_pas_comme_si_on_passait_pour_des_glands_tous_les_jours.mp3"
    , "kaamelott/cest_pas_des_fleches.mp3"
    , "kaamelott/cest-pas-du-burgonde-ca.mp3"
    , "kaamelott/cest-pas-du-tout-mon-anniversaire.mp3"
    , "kaamelott/cest_pas_faux1.mp3"
    , "kaamelott/cest_pas_faux2.mp3"
    , "kaamelott/cest_pas_jo_le_rigolo.mp3"
    , "kaamelott/c_est_pas_parce_qu_ils_ont_trahi_que_c_est_plus_des_allies.mp3"
    , "kaamelott/cest-pas-pour-rien-quon-mappelle-le-fourbe.mp3"
    , "kaamelott/cest_pas_une_sinecure.mp3"
    , "kaamelott/cest-personne-un-connard.mp3"
    , "kaamelott/cest_plus_filiforme.mp3"
    , "kaamelott/cest-pour-voir-si-vous-avez-un-don.mp3"
    , "kaamelott/cest_prodigieux.mp3"
    , "kaamelott/cest_que_cest_pas_une_blague.mp3"
    , "kaamelott/cest_qui_tout_ces_cons.mp3"
    , "kaamelott/cest_tellement_facile_que_je_vais_peut_etre_systematise_le_processus.mp3"
    , "kaamelott/cest_toujours_un_peu_delicat_de_parler_damour_aux_cons.mp3"
    , "kaamelott/cest-une-blague.mp3"
    , "kaamelott/cest_une_catastrophe_souffle.mp3"
    , "kaamelott/cest-un-scandale.mp3"
    , "kaamelott/cest_vrai_quelle_reste.mp3"
    , "kaamelott/chaque_fois_que_je_vais_a_un_balloche_je_picole_je_discute.mp3"
    , "kaamelott/charmant.mp3"
    , "kaamelott/chevalierisation.mp3"
    , "kaamelott/chui_un_marteau_moi.mp3"
    , "kaamelott/comme-la-mare-aux-canards.mp3"
    , "kaamelott/commencez_pas_a_me_faire_chier.mp3"
    , "kaamelott/Comment_ca_on_bute_Karadoc.mp3"
    , "kaamelott/comment.mp3"
    , "kaamelott/comment_peut_on_arriver_a_un_grade_aussi_eleve.mp3"
    , "kaamelott/compote.mp3"
    , "kaamelott/comprend_jamais_un_broc_de_ce_quon_dit.mp3"
    , "kaamelott/considerer_que_je_suis_officiellement_cul_nu.mp3"
    , "kaamelott/coup_de_beche.mp3"
    , "kaamelott/coup_de_pied_aux_poules.mp3"
    , "kaamelott/crame_ta_famille.mp3"
    , "kaamelott/cuillere_2.mp3"
    , "kaamelott/cuillere.mp3"
    , "kaamelott/cuit_les_boules.mp3"
    , "kaamelott/dans_la_vie.mp3"
    , "kaamelott/dans_trois_jours_cest_les_vacances.mp3"
    , "kaamelott/dans_trois_jours_ma_tata_elle_menmene_a_la_mer_pour_me_noyer.mp3"
    , "kaamelott/decarre-tes-troupes-de-chez-moi-ou-je-crame-ton-pays.mp3"
    , "kaamelott/degaine-crevette-merou.mp3"
    , "kaamelott/deja_que_ca_me_gonfle_de_porter_des_messages.mp3"
    , "kaamelott/demain-cest-demain.mp3"
    , "kaamelott/demi_journee_vous_attend.mp3"
    , "kaamelott/de_quoi_desole_excusez_moi_j_ecoutais_pas.mp3"
    , "kaamelott/des-betes-sauvages-que-je-vais-recuperer.mp3"
    , "kaamelott/des_fois_on_a_pas_le_choix_faut_sacrifier_les_jeunes.mp3"
    , "kaamelott/des_pedales_ils_disent_sur_le_message.mp3"
    , "kaamelott/des_vetements.mp3"
    , "kaamelott/de-toute-facon-les-reunions-cest-2-fois-par-mois.mp3"
    , "kaamelott/de_tout_facon_on_dit_le_nord_selon_comment_on_est_tourne_ca_change_tout.mp3"
    , "kaamelott/deux_trous_du_cul_soient_plus_efficaces_qu_un_seul.mp3"
    , "kaamelott/difference_concrete_avec_des_briques.mp3"
    , "kaamelott/dis_donc_machine_si_tu_allais_voir_a_la_table_du_fond_si_on_y_ait.mp3"
    , "kaamelott/dites_tirez_vous.mp3"
    , "kaamelott/dites_tout_de_suite_que_j_ai_des_idees_de_tocard.mp3"
    , "kaamelott/donc-cette-fiole.mp3"
    , "kaamelott/donc-vous-allez-faire-une-troupe-delite-avec-vos-cousins-debiles.mp3"
    , "kaamelott/ebaubir.mp3"
    , "kaamelott/ecartez-vous.mp3"
    , "kaamelott/ecoutez_je_comprend_rien_a_ce_que_vous_faites.mp3"
    , "kaamelott/elle_avait_choppe_toutes_les_maladies.mp3"
    , "kaamelott/elle_avait_rien_a_y_foutre_deja_pour_commencer.mp3"
    , "kaamelott/elle_est_ou_la_poulette.mp3"
    , "kaamelott/elle-me-fixe-avec-ses-yeux-de-serpent.mp3"
    , "kaamelott/elle_vomit.mp3"
    , "kaamelott/embobinage_dans_l_air.mp3"
    , "kaamelott/en-fait-jetais-dans-un-paturage.mp3"
    , "kaamelott/enfin-quand-cest-demande-gentiment.mp3"
    , "kaamelott/en_garde_espece_de_vieille_pute_degarnie.mp3"
    , "kaamelott/en_garde_ma_mignone.mp3"
    , "kaamelott/enquille.mp3"
    , "kaamelott/entre-le-roi-arthur-quest-pas-capable-de-denicher-son-graal.mp3"
    , "kaamelott/epique.mp3"
    , "kaamelott/essayez_de_faire_des_phrases_pour_vous_deja.mp3"
    , "kaamelott/est_ce_que_peut_servir_elan_pigeon.mp3"
    , "kaamelott/est-ce-que-vous-allez-finir-par-fermer-vos-gueules.mp3"
    , "kaamelott/est-ce_que_vous_pouvez_vous_barrer_maintenant.mp3"
    , "kaamelott/est_ce_quil_sait_nager_deja.mp3"
    , "kaamelott/et_alors_faut_un_permis.mp3"
    , "kaamelott/et_a_un_moment_le_sorcier_s_est_mis_a_nous_menacer_avec_ses_parties_genitales.mp3"
    , "kaamelott/et-bah-tu-peux-te-la-garder.mp3"
    , "kaamelott/et-ca-cest-du-nougat.mp3"
    , "kaamelott/et-celle-la-jirai-pas-me-coucher-avant-de-lavoir-bousillee.mp3"
    , "kaamelott/et_cest_de_la_merde.mp3"
    , "kaamelott/et-moi-je-me-suis-fait-derober-de-lalimentation-tout-le-long-du-voyage.mp3"
    , "kaamelott/et-oui-meme-t-es-bien-mouchee.mp3"
    , "kaamelott/et_puis_alors_mon_petit_pote_si_vous_en_tenez_une_qui_veux_se_marier_avec_vous.mp3"
    , "kaamelott/et_puis_quoi_encore.mp3"
    , "kaamelott/et_puis_y_a_toujours_une_proportion_de_secoues.mp3"
    , "kaamelott/et_si_vous_arretiez_de_gueuler.mp3"
    , "kaamelott/et_vous_bande_de_cons.mp3"
    , "kaamelott/euh_donc_pour_le_moment_on_le_crame_pas.mp3"
    , "kaamelott/euh-si-il-lache-une-caisse-ca-le-fait-ou-pas.mp3"
    , "kaamelott/evidemment_quelquun.mp3"
    , "kaamelott/evitez-de-mappeler-maman.mp3"
    , "kaamelott/exagerer_non.mp3"
    , "kaamelott/excusez_moi_hein_je_ne_connais_pas_encore_bien_vos_noms.mp3"
    , "kaamelott/fagot_fagot_fagot.mp3"
    , "kaamelott/faisons_table_en_marbre.mp3"
    , "kaamelott/faites_gaffe_aux_pieges_a_loups.mp3"
    , "kaamelott/faites-pas-le-con-sire-ouvrez.mp3"
    , "kaamelott/faut_ce_qui_faut.mp3"
    , "kaamelott/faut_que_je_retourne_a_la_ferme_de_mes_vieux.mp3"
    , "kaamelott/faut-y-aller-a-la-zob.mp3"
    , "kaamelott/federer_mes_couilles.mp3"
    , "kaamelott/fer-a-cheval.mp3"
    , "kaamelott/ferme_ta_gueule.mp3"
    , "kaamelott/fier_je_vais_l_envoyer_trois_mois_a_poil_dans_la_foret.mp3"
    , "kaamelott/fils_d_unijambiste.mp3"
    , "kaamelott/fiotte-tatie.mp3"
    , "kaamelott/fleur_en_bouquet.mp3"
    , "kaamelott/fort_en_pomme_1.mp3"
    , "kaamelott/fort_en_pomme_2.mp3"
    , "kaamelott/fournis_notice.mp3"
    , "kaamelott/franchement-une-potion-pour-faire-pisser-bleu.mp3"
    , "kaamelott/fumier.mp3"
    , "kaamelott/gerber-mourir.mp3"
    , "kaamelott/gigoter_des_miches_ca_donne_faim.mp3"
    , "kaamelott/gras_du_cul.mp3"
    , "kaamelott/gras-sur-le-cul.mp3"
    , "kaamelott/hein_titi.mp3"
    , "kaamelott/he_les_connards_vous_pouvez_faire_griller_un_porcelet.mp3"
    , "kaamelott/heu_cest_plutot_des_cons.mp3"
    , "kaamelott/Homme-sans-metier.mp3"
    , "kaamelott/honnetement_je_connais_pas_le_mot_la.mp3"
    , "kaamelott/humilite_infiltration.mp3"
    , "kaamelott/ici_chez_les_salopards.mp3"
    , "kaamelott/il_avait_une_touffe_de_cheveux_comme_ca_un_vieux_moisi_tout_gueze_a_poil_dans_la_neige.mp3"
    , "kaamelott/il_est_coince_ce_con_la.mp3"
    , "kaamelott/il-est-fort-le-salaud.mp3"
    , "kaamelott/il_est_pas_beau_mon_graal.mp3"
    , "kaamelott/il-faut-affranchir-nos-compagnons.mp3"
    , "kaamelott/il_m_aura_fait_chier_jusqu_au_bout_celui_la.mp3"
    , "kaamelott/il_ne_comprennent_jamais_le_code.mp3"
    , "kaamelott/il_nous_a_chie_dessus.mp3"
    , "kaamelott/il-n-y-a-pas-dequivoque-vous-etes-franchement-un-bourrin.mp3"
    , "kaamelott/il-n-y-a-rien-a-prier.mp3"
    , "kaamelott/il-parle-pas-il-bouge-pas-il-fait-la-gueule-tout-le-temps.mp3"
    , "kaamelott/il_pige_rien_a_rien.mp3"
    , "kaamelott/il_pue_il_pete.mp3"
    , "kaamelott/il_ressemble_a_tatan.mp3"
    , "kaamelott/ils-commencent-a-doucement-me-faire-chier-ceux-la-aussi.mp3"
    , "kaamelott/ils-commencent-par-apprendre-a-lire.mp3"
    , "kaamelott/ils_se_barrent_en_mission_pendant_trois_mois_et_ils_reviennent_avec_une_anguille.mp3"
    , "kaamelott/ils-se-sont-pas-leve-1.mp3"
    , "kaamelott/ils-se-sont-pas-leve-2.mp3"
    , "kaamelott/ils-se-sont-pas-leve-3.mp3"
    , "kaamelott/ils_sortent_bien_de_quelques_part.mp3"
    , "kaamelott/il_trouverait_meme_pas_sa_bite_pour_pisser.mp3"
    , "kaamelott/inattendu.mp3"
    , "kaamelott/incandescent.mp3"
    , "kaamelott/insipide.mp3"
    , "kaamelott/insoupconnable.mp3"
    , "kaamelott/interprete.mp3"
    , "kaamelott/intro_comaque.mp3"
    , "kaamelott/jai_arrete_les_pronostics.mp3"
    , "kaamelott/j-ai-cherche-la-merde.mp3"
    , "kaamelott/j_ai_fais_pile_comme_vous_avez_dis_tout_au_feu_de_bois.mp3"
    , "kaamelott/jai-jamais-entendu-le-son-de-sa-voix.mp3"
    , "kaamelott/j_ai_le_droit_d_etre_4_jours_pas_chez_moi.mp3"
    , "kaamelott/jai-le-droit-detre-4-jours-pas-chez-moi.mp3"
    , "kaamelott/j_aimerais_bien_qu_on_commence_a_me_considerer_en_tant_que_tel.mp3"
    , "kaamelott/jai_pas_envie_de_voir_vos_tronches.mp3"
    , "kaamelott/j_ai_pas_eu_le_temps_d_enlever_mon_armure.mp3"
    , "kaamelott/jai_rien_compris.mp3"
    , "kaamelott/jai_toujours_ete_fascine_par_le_monde_paysan.mp3"
    , "kaamelott/j-ai-tout-entendu.mp3"
    , "kaamelott/j_apprecie_les_fruits_au_sirop.mp3"
    , "kaamelott/je_connais_que_le_cri.mp3"
    , "kaamelott/je_crois_pas_que_vous_soyez_le_symbole_de_la_nation_bretonne.mp3"
    , "kaamelott/je-l-ai-pas-dit-fort.mp3"
    , "kaamelott/je_l_ai_perdu.mp3"
    , "kaamelott/je-moccupe-de-tout-dite-oui.mp3"
    , "kaamelott/j_en_ai_rien_a_foutre_je_dors_dans_la_tente_du_roi.mp3"
    , "kaamelott/j_en_ai_rien_a_foutre.mp3"
    , "kaamelott/je_ne_mange_pas_de_graines.mp3"
    , "kaamelott/je_pourrais_gueuler_dans_le_cul_dun_poney.mp3"
    , "kaamelott/je_refuse_daller_me_battre.mp3"
    , "kaamelott/je_sens_que_ce_va_encore_etre_capital.mp3"
    , "kaamelott/je-suis-desole-jai-pas-eu-le-temps-de-potasser-les-formules.mp3"
    , "kaamelott/je_trouve_qu_on_nous_prend_un_peu_trop_pour_des_cons.mp3"
    , "kaamelott/je_vais_devenir_paladin.mp3"
    , "kaamelott/je_vais_pas_faire_des_aller_retours_3_fois_par_jours.mp3"
    , "kaamelott/je_vais_vous_passer_le_gout_du_plein_air_moi.mp3"
    , "kaamelott/je_veux_mhabiller_de_lierre_et_me_coiffer_de_roseaux.mp3"
    , "kaamelott/je_vois.mp3"
    , "kaamelott/je_vois_pas_le_rapport_avec_bretagne.mp3"
    , "kaamelott/je_vois_trouble.mp3"
    , "kaamelott/je-vous-ai-toujours-dit-ce-que-vous-faites-avec-les-chiffres.mp3"
    , "kaamelott/je_vous_disais_que_j_etais_victime_des_colifiches.mp3"
    , "kaamelott/joie_de_vivre.mp3"
    , "kaamelott/jpeux_pas_vous_dire.mp3"
    , "kaamelott/jsais_pas_cqui_vous_faut.mp3"
    , "kaamelott/jsuis_a_mon_poste_cest_pas_le_cas_de_tout_le_monde.mp3"
    , "kaamelott/jsuis_chef_de_guerre.mp3"
    , "kaamelott/jvoudrais_pas_faire_ma_raclette.mp3"
    , "kaamelott/jvous_fait_confiance.mp3"
    , "kaamelott/jy_vais_javoine.mp3"
    , "kaamelott/kaamelott_cest_pas_une_cooperative_bovine.mp3"
    , "kaamelott/karadoc-cest-le-gars-brillant.mp3"
    , "kaamelott/la-blague-est-pas-drole.mp3"
    , "kaamelott/la_bouffe_est_interdite.mp3"
    , "kaamelott/la-cest-sur-vu-les-tronche-que-vous-tirez.mp3"
    , "kaamelott/lache_une_caisse.mp3"
    , "kaamelott/la-chevre-a-beler-5-min.mp3"
    , "kaamelott/la_dedans_carbure.mp3"
    , "kaamelott/la_gerbe.mp3"
    , "kaamelott/lair_idiote.mp3"
    , "kaamelott/laissez_le_a_lair.mp3"
    , "kaamelott/la_monstruosite.mp3"
    , "kaamelott/la-tournure-est-plus-graduelle.mp3"
    , "kaamelott/la_vache_ca_daube_la_dedans_il_y_a_un_chat_qui_est_creve_ou_quoi.mp3"
    , "kaamelott/la-vue-du-bourgeois-ca-me-fait-de-laerophagie.mp3"
    , "kaamelott/le_caca_des_pigeons_c_est_caca_faut_pas_manger.mp3"
    , "kaamelott/le_graal_par_ci_le_graal_par_la.mp3"
    , "kaamelott/le_gras_cest_la_vie.mp3"
    , "kaamelott/le-plus-interessant-cest-comment-vous-arrivez-a-faire-un-truc-aussi-immonde.mp3"
    , "kaamelott/le_pognon_ca_va_ca_vient.mp3"
    , "kaamelott/le_poisson_le_petit_poisson.mp3"
    , "kaamelott/le_prochain_qui_l_ouvre_galeres_trois_ans.mp3"
    , "kaamelott/les-chevaliers-de-mes-deux.mp3"
    , "kaamelott/le-seigneur-perceval-ne-se-met-jamais-en-situation-dangeureuse.mp3"
    , "kaamelott/les-femmes-jaime-pas-ca-c'est-de-la-saloperie.mp3"
    , "kaamelott/les-gars-me-regardent-avec-des-billes-comme-ca-et-ils-decrochent.mp3"
    , "kaamelott/les_pattes_de_canard.mp3"
    , "kaamelott/Les-petits-pedestres-dont-un-au-lion.mp3"
    , "kaamelott/Les-petits-pedestres.mp3"
    , "kaamelott/les_premieres_oeillades.mp3"
    , "kaamelott/le-votre-aussi-cest-de-la-merde.mp3"
    , "kaamelott/lui_on_comprend_ni_ce_qu_il_dit_ni_ce_qu_il_fait.mp3"
    , "kaamelott/madresse_pas_la_parole.mp3"
    , "kaamelott/ma_femme_a_pas_de_moustache.mp3"
    , "kaamelott/maintenant-il-faut-nous-ecouter-parce-que-la-on-en-a-gros.mp3"
    , "kaamelott/mais_allez_chier_dans_une_fiolle.mp3"
    , "kaamelott/mais-allez-y-cest-pour-vous-stimuler-bon-dieu.mp3"
    , "kaamelott/mais-allez-y-magnez-vous-le-fion-espece-de-grosse-dinde.mp3"
    , "kaamelott/mais_arretez_de_discutailler_cinq_minutes.mp3"
    , "kaamelott/mais-cest-de-la-merde.mp3"
    , "kaamelott/mais-cest-incroyable-jai-limpression-de-bouffer-de-la-terre.mp3"
    , "kaamelott/mais-cest-pas-complique-quand-vous-voyez-des-gadins.mp3"
    , "kaamelott/mais_c_est_pas_possible_d_entendre_ca.mp3"
    , "kaamelott/mais_c_est_une_honte_d_entendre_des_trucs_comme_ca.mp3"
    , "kaamelott/mais-compare-a-ce-quon-a-trouve.mp3"
    , "kaamelott/mais-evidemment-cest-sans-alcool.mp3"
    , "kaamelott/mais_evidemment_que_si.mp3"
    , "kaamelott/mais_faut_pas_deconner_ils_y_sont_pour_rien.mp3"
    , "kaamelott/mais-je-le-sais-bien-que-vous-avez-pas-les-cles-andouille.mp3"
    , "kaamelott/mais_je_vous_ai_dis_que_c_etait_important.mp3"
    , "kaamelott/mais_je_vous_emmerde_mon_ptit_pote.mp3"
    , "kaamelott/mais_mariez_vous_avec_qui_vous_voulez_et_allez_crever.mp3"
    , "kaamelott/mais_moi_je_vous_previens_jy_connais_rien_en_champignon.mp3"
    , "kaamelott/mais-non-qu-est-ce-que-jen-ai-a-carrer.mp3"
    , "kaamelott/mais-pas-du-tout.mp3"
    , "kaamelott/mais_qu_est_ce_que_j_en_ai_a_foutre.mp3"
    , "kaamelott/mais_qu_est_ce_que_j_en_ai_a_foutre_vous_pourriez_bien_vous_marier_avec_une_chevre_si_ca_vous_chante.mp3"
    , "kaamelott/mais_qu_est_ce_que_vous_me_bavez_encore.mp3"
    , "kaamelott/mais-qu-est-ce-que-vous-venez-me-gonfler-avec-votre-pere-blaise.mp3"
    , "kaamelott/mais_qu_est_ce_que_vous_voulez_que_ca_me_foute.mp3"
    , "kaamelott/mais_qu_est_ce_que_vous_voulez_que_ca_me_foute_vos_conneries.mp3"
    , "kaamelott/mais-qu-est-ce-que-vous-voulez-quon-en-foute-de-vos-peigne-culs.mp3"
    , "kaamelott/mais_qu_est_ce_qui_vous_prend_ca_va_pas_vous_etes_dingue.mp3"
    , "kaamelott/mais_si_on_fait_marrer_tout_le_monde.mp3"
    , "kaamelott/mais_tout_a_fait.mp3"
    , "kaamelott/mais-vous-etes-pas-mort-espece-de-connard.mp3"
    , "kaamelott/mais-vous-guidez-que-dalle.mp3"
    , "kaamelott/mais_vous_savez_ce_que_ca_veux_dire_au_moins.mp3"
    , "kaamelott/mais_ya_rien_a_developper_cest_de_la_merde_cest_tout.mp3"
    , "kaamelott/malademental.mp3"
    , "kaamelott/malediction_tous_petits_pets.mp3"
    , "kaamelott/mavez_lair_en_forme.mp3"
    , "kaamelott/mavez_lair_en_forme_vous_ce_soir.mp3"
    , "kaamelott/mecreant_2.mp3"
    , "kaamelott/mecreant.mp3"
    , "kaamelott/me_parler_a_cette_heure_ci_vous_voulez_mon_pied_au_cul.mp3"
    , "kaamelott/merci_de_rien.mp3"
    , "kaamelott/merciiiii.mp3"
    , "kaamelott/merde-la-ca-vous-va-ca.mp3"
    , "kaamelott/mes_endives.mp3"
    , "kaamelott/meteo.mp3"
    , "kaamelott/mettre_du_beurre_au_fond_du_plat.mp3"
    , "kaamelott/mi_ours_mi_scorpion.mp3"
    , "kaamelott/mochete-en-plus-quand-on-voit-le-morceau-quil-se-trimballe.mp3"
    , "kaamelott/moi_a_lepoque_je_voulais_faire_voeux_de_pauvrete_--_et_alors__--_ben_avec_le_pognon_que_j.mp3"
    , "kaamelott/moi_depuis_ce_matin_je_me_fait_traiter_de_gonzesse.mp3"
    , "kaamelott/moi_il_faut_que_j_enleve_mon_armure.mp3"
    , "kaamelott/moi_jai_toujours_dit2.mp3"
    , "kaamelott/moi_jai_toujours_dit.mp3"
    , "kaamelott/moi-je-serais-vous-je-vous-ecouterais.mp3"
    , "kaamelott/moi_je_serais_vous_je_vous_ecouterais.mp3"
    , "kaamelott/moi_non_plus_je_vois_rien.mp3"
    , "kaamelott/moi-pour-quon-me-reconnaisse-faut-juste-2-3-coups-de-pinceaux.mp3"
    , "kaamelott/mon_frere_y_peut_pas_aller_a_l_ecole.mp3"
    , "kaamelott/mordu.mp3"
    , "kaamelott/nan-ca-va-pas-etre-possible-ca.mp3"
    , "kaamelott/nan-cest-nimporte-quoi.mp3"
    , "kaamelott/nan_la_sans_deconner_cest_zero.mp3"
    , "kaamelott/nan_mais_c_est_pas_possible_elle_me_foutra_pas_la_paix.mp3"
    , "kaamelott/nan-mais-en-vrai-pas-sur-la-carte.mp3"
    , "kaamelott/nan-mais-par-contre-ils-sont-super-cons.mp3"
    , "kaamelott/nan-mais-quand-meme.mp3"
    , "kaamelott/nan-nan-nous-on-est-pas-fixe.mp3"
    , "kaamelott/nempeche_que_cest_moi_qui_avait_propose.mp3"
    , "kaamelott/ne_te_mets_pas_en_dehors_du_chemin_de_la_redemption.mp3"
    , "kaamelott/ni_vu_ni_connu.mp3"
    , "kaamelott/non-il-est-degueulasse-celui-la.mp3"
    , "kaamelott/non-mais-biensur-donc-vous-vous-degommez-les-souris-au-maillet.mp3"
    , "kaamelott/non-mais-franchement-je-serais-nous-je-vous-ecouterais.mp3"
    , "kaamelott/non_mais_je_sens_bien_que_vous_essayer_de_me_dire_quelque_chose.mp3"
    , "kaamelott/non-mais-vous-pouvez-la-distraire-avec-un-numero-de-jonglage.mp3"
    , "kaamelott/non-on-a-fait-3-bornes-sil-vous-plait.mp3"
    , "kaamelott/non_psychologique_c_est_tout_ce_qui_est_a_la_campagne.mp3"
    , "kaamelott/non_taisez_vous.mp3"
    , "kaamelott/notre-enchanteur-minforme-que-dhabitude-il-y-arrive-tres-bien.mp3"
    , "kaamelott/nous-on-foule-le-fruit-avec-nos-propres-pieds.mp3"
    , "kaamelott/nuo_pusso_volo.mp3"
    , "kaamelott/oh-bah-oui-vous-en-etes-une-belle-forme-durticaire.mp3"
    , "kaamelott/oh_ca_fait_rien.mp3"
    , "kaamelott/oh_cest_la_vacherie_ca.mp3"
    , "kaamelott/oh_et_puis_j_en_ai_marre.mp3"
    , "kaamelott/oh-la-vache-mais-cest-nul.mp3"
    , "kaamelott/oh_la_vache.mp3"
    , "kaamelott/oh-mais-vous-etes-des-malades.mp3"
    , "kaamelott/oh-non-mais-il-y-a-des-jours-vous-deconnez-sec.mp3"
    , "kaamelott/oh_putain_oui.mp3"
    , "kaamelott/ok_on_va_arreter_le_tire_avec_les_defis.mp3"
    , "kaamelott/on_a_pas_regarde_dans_les_f.mp3"
    , "kaamelott/on_en_a_gros.mp3"
    , "kaamelott/on_essaie_de_catapulter_un_danseur.mp3"
    , "kaamelott/on_est_forts.mp3"
    , "kaamelott/on-est-indestructible.mp3"
    , "kaamelott/on_est_pas_sorti_du_sable.mp3"
    , "kaamelott/on_fera_tintin_pour_le_clafoutis.mp3"
    , "kaamelott/on-pisse-pas-contre-les-murs-de-la-chapelle-cest-clair.mp3"
    , "kaamelott/on_plaisante_on_plaisante.mp3"
    , "kaamelott/ouais_ca_aussi.mp3"
    , "kaamelott/ouais-cest-grace-a-notre-arme-secrete.mp3"
    , "kaamelott/ouais_cest_mortel_ouais.mp3"
    , "kaamelott/oui_ben_non.mp3"
    , "kaamelott/oui_enfin_je_me_comprends.mp3"
    , "kaamelott/oui_et_ben_moi_je_vous_donne_lordre_de_lui_preter_votre_corne_parce_que_quand_on_est_gentil_on_prete.mp3"
    , "kaamelott/oui.mp3"
    , "kaamelott/oui_oh_ca_va_je_connais_le_couplet_on_est_fatigue_on_est_fatigue_vous_me_le_cancane_depuis_midi.mp3"
    , "kaamelott/oui_ou_une_fissure_a_colmater_dans_un_muret.mp3"
    , "kaamelott/oui-peut-etre-oui-oui.mp3"
    , "kaamelott/parce_que_la_quite_a_se_faire_reperer_on_prendrait_moins_de_risque_a_faire_venir_un_orchestre.mp3"
    , "kaamelott/parce-que-vous-etes-en-train-de-faire-une-connerie-la-quand-meme.mp3"
    , "kaamelott/par-contre-il-est-hyper-con-je-sais-pas-pourquoi.mp3"
    , "kaamelott/parfaitement_antipathique.mp3"
    , "kaamelott/parle_de_travers_cureton.mp3"
    , "kaamelott/pas_dalcool.mp3"
    , "kaamelott/pas_de_quoi_en_chier_une_galette.mp3"
    , "kaamelott/pas_du_tout_les_lapins_les_lapins_c_est_gentil.mp3"
    , "kaamelott/pas_envie_de_participer.mp3"
    , "kaamelott/pas_foutu_de_savoir_son_nom.mp3"
    , "kaamelott/pas_la_moindre_idee.mp3"
    , "kaamelott/pas-moyen-de-lui-faire-fermer-sa-gueule.mp3"
    , "kaamelott/pas-moyen-de-piger-un-broc-de-ce-quil-dit.mp3"
    , "kaamelott/patience-plat-sans-sauce.mp3"
    , "kaamelott/pauvre_conne.mp3"
    , "kaamelott/pays_de_galles_independant.mp3"
    , "kaamelott/peigne_zizi.mp3"
    , "kaamelott/petit_a_petit_vers_plus_dautonomie.mp3"
    , "kaamelott/petite_corne.mp3"
    , "kaamelott/petit_ton_decale.mp3"
    , "kaamelott/peur_justifiee.mp3"
    , "kaamelott/peut-etre-meme-que-je-mette-une-armure.mp3"
    , "kaamelott/pfff_c_est_pour_ca_que_je_pane_rien_aux_livres_moi_ca_veut_pas_dire_ce_qu_il_y_a_marque.mp3"
    , "kaamelott/pfiou-pfiou-pfiou.mp3"
    , "kaamelott/pique_diagonale.mp3"
    , "kaamelott/pires-trucs-reparation.mp3"
    , "kaamelott/plait_il.mp3"
    , "kaamelott/plus-trop-parler.mp3"
    , "kaamelott/politique_de_l_autruche.mp3"
    , "kaamelott/pour_le_detail_je_sais_pas.mp3"
    , "kaamelott/pourquoi_pas1.mp3"
    , "kaamelott/pourquoi_pas2.mp3"
    , "kaamelott/pourquoi_qu_on_gueule.mp3"
    , "kaamelott/pourquoi-voulez-vous-que-je-pense-a-la-reine.mp3"
    , "kaamelott/pour_savoir_si_il_va_y_avoir_du_vent.mp3"
    , "kaamelott/ptetre_une_connerie.mp3"
    , "kaamelott/ptite_pucelle.mp3"
    , "kaamelott/putain_faut_vraiment_qu_on_se_groulle.mp3"
    , "kaamelott/putain_il_est_fort_ce_con.mp3"
    , "kaamelott/quand-il-a-rien-a-dire-il-dit-rien.mp3"
    , "kaamelott/quand_je_comprends_pas_je_reponds_pas.mp3"
    , "kaamelott/quand_meme_raide.mp3"
    , "kaamelott/quand_on_gueule_sans_savoir_pourquoi.mp3"
    , "kaamelott/quand_on_se_fache.mp3"
    , "kaamelott/quequette.mp3"
    , "kaamelott/qu-est_ce_dire_que_ceci.mp3"
    , "kaamelott/quest-ce-que-cest-ce-nouveau-genre-seigneur-lancelot.mp3"
    , "kaamelott/qu-est-ce-que-cest-cette-tisane.mp3"
    , "kaamelott/qu-est-ce-que-je-suis-en-train-de-faire-avec-mon-doigt.mp3"
    , "kaamelott/quest_ce_que_vous_attendez_pour_la_couper.mp3"
    , "kaamelott/quest-ce-que-vous-racontez-cest-pas-ca.mp3"
    , "kaamelott/quest-ce-que-vous-voulez-que-ca-me-foute.mp3"
    , "kaamelott/qu_est_ce_que_vous_voulez_savoir_allez_vous_vous_magner_le_tronc_maintenant.mp3"
    , "kaamelott/qu-est-ce-qui-a-dautre-qui-pue-sinon.mp3"
    , "kaamelott/quest_ce_qui_est_petit_et_marron.mp3"
    , "kaamelott/quicher-tete.mp3"
    , "kaamelott/quies.mp3"
    , "kaamelott/quoi-bah-mon-cochon-vous-manquez-pas-de-cran.mp3"
    , "kaamelott/quoi-mais-cest-un-scandale.mp3"
    , "kaamelott/rangez_moi_ca_debile_la_table_ronde_c_est_pas_une_fete_de_l_artisanat.mp3"
    , "kaamelott/ratisser-bouse-torcher-cul-poules.mp3"
    , "kaamelott/regardez_moi_ce_petit_navet.mp3"
    , "kaamelott/regardez_moi_cette_meule.mp3"
    , "kaamelott/remarquez-jai-un-pote-poissonier.mp3"
    , "kaamelott/remonte-ton-slibard.mp3"
    , "kaamelott/Ren_dez_vous_a_la_ta_verne_incognito.mp3"
    , "kaamelott/restez_pas_plante_la_comme_un_cepe.mp3"
    , "kaamelott/rien_a_carer.mp3"
    , "kaamelott/rien_a_carrer.mp3"
    , "kaamelott/rien-ca-fait-rien-cassez-vous.mp3"
    , "kaamelott/rooo_bon_alors_on_fait_venir_les_poulettes_ou_quoi.mp3"
    , "kaamelott/salut-sire-je-trouve-quil-fait-beau-mais-encore-frais-mais-beau.mp3"
    , "kaamelott/sans_blague_ya_pas_dla_gourdasse.mp3"
    , "kaamelott/sans-deconner-faut-pas-y-aller-demain.mp3"
    , "kaamelott/sans_deconner.mp3"
    , "kaamelott/sans_etre_totalement_repoussant_il_n_y_a_pas_de_quoi_bousculer_une_charette.mp3"
    , "kaamelott/scorpion_entoure_par_le_feu.mp3"
    , "kaamelott/seigneur-bohort-je-commence-a-en-avoir-plein-le-dos.mp3"
    , "kaamelott/signe_de_vouloir_discuter.mp3"
    , "kaamelott/si_j_etais_tombe_sur_un_faisant.mp3"
    , "kaamelott/sils_sont_equidistants_on_peut_reperer_le_dragon.mp3"
    , "kaamelott/simple_deduction_mon_oncle.mp3"
    , "kaamelott/sinon_ce_que_je_peux_vous_proposer_on_attache_le_condamne.mp3"
    , "kaamelott/si-on-peut-sen-farcir-un-cest-toujours-ca-de-pris-quoi.mp3"
    , "kaamelott/sire-je-ne-suis-pas-homme.mp3"
    , "kaamelott/sire_vous_me_flattez.mp3"
    , "kaamelott/si_vous_etes_vendeur.mp3"
    , "kaamelott/sortez-vous_les_doigts_du_cul.mp3"
    , "kaamelott/soupcon_gros_nul.mp3"
    , "kaamelott/sourire_comme_des_glands.mp3"
    , "kaamelott/Soyez-souple-un-peu.mp3"
    , "kaamelott/stand_de_crepes.mp3"
    , "kaamelott/sur_de_son_coup.mp3"
    , "kaamelott/tais_toi_ta_gueule_tais_toi.mp3"
    , "kaamelott/tape-la-honte.mp3"
    , "kaamelott/tatan_elle_fait_des_flans.mp3"
    , "kaamelott/tempora_mori.mp3"
    , "kaamelott/tete-roupiller-couloir.mp3"
    , "kaamelott/toujours_se_plaindre_pequenauds.mp3"
    , "kaamelott/tout_dans_le_furtif.mp3"
    , "kaamelott/tout_le_monde_s_en_branle_moi_le_premier.mp3"
    , "kaamelott/Tout-travail-merite-salaire.mp3"
    , "kaamelott/tres_bien.mp3"
    , "kaamelott/tres_en_colere.mp3"
    , "kaamelott/trois_jours_voyages_trois_jours_chez_vous.mp3"
    , "kaamelott/tropgentil.mp3"
    , "kaamelott/tsoin-tsoin.mp3"
    , "kaamelott/tu_la_fermes_definitivement.mp3"
    , "kaamelott/tu-ne-tuera-point.mp3"
    , "kaamelott/un_bon_quart_dheure.mp3"
    , "kaamelott/une_claque_dans_le_museau_vous_repondez.mp3"
    , "kaamelott/une_fois_a_une_execution_je_m_approche_d_une_fille.mp3"
    , "kaamelott/un_genre_cake.mp3"
    , "kaamelott/un_jour_je_vais_lui_fumer_sa_gueule_a_ce_connard.mp3"
    , "kaamelott/un_plan_d_attaque_minute_au_poil_de_fion.mp3"
    , "kaamelott/urgan-lhomme-goujon.mp3"
    , "kaamelott/venez-mouvriiir.mp3"
    , "kaamelott/venir_foutre_votre_merde.mp3"
    , "kaamelott/victoriae_mundis.mp3"
    , "kaamelott/voeux_de_pauvrete_jarrivais_pas_a_concilier.mp3"
    , "kaamelott/voila_cest_pro.mp3"
    , "kaamelott/voila_passez_moi_la_canne_a_peche.mp3"
    , "kaamelott/voila_zut.mp3"
    , "kaamelott/votre_existence_est_merdique.mp3"
    , "kaamelott/vous_admettrez_que_vous_etes_hors_normes.mp3"
    , "kaamelott/vous_allez_fermer_vos_mouilles_oui.mp3"
    , "kaamelott/vous_allez_me_foutre_le_camp_espece_de_con.mp3"
    , "kaamelott/vous_allez_me_lacher_les_noyaux_oui.mp3"
    , "kaamelott/vous-allez-me-montrer-ce-que-vous-avez-un-peu-dans-le-froc.mp3"
    , "kaamelott/vous-allez-me-promettre-de-pas-y-foutre-les-pieds.mp3"
    , "kaamelott/vous_allez_pas_commencer_avec_vos_termes_pourris.mp3"
    , "kaamelott/vous_avez_pas_limpression_que_je_suis_dans_une_baignoire.mp3"
    , "kaamelott/vous-avez-pas-pris-le-temps-de-vous-habituer-au-fruit.mp3"
    , "kaamelott/vous_balader_avec_une_cuillere_a_soupe_ca_changerait_rien.mp3"
    , "kaamelott/vous_cassez_pas_la_nenette_pour_moi.mp3"
    , "kaamelott/vous_comprenez_le_principe.mp3"
    , "kaamelott/vous_deconnez.mp3"
    , "kaamelott/vous_devriez_commencer_par_organiser_le_merdier_que_vous_avez_la_dedans.mp3"
    , "kaamelott/vous-en-mettez-pas-trop.mp3"
    , "kaamelott/vous_etes_completement_con.mp3"
    , "kaamelott/vous_etes_des_damnes.mp3"
    , "kaamelott/vous-etes-une-gigantesque-tarlouze.mp3"
    , "kaamelott/vous_etes_un_gros_nul.mp3"
    , "kaamelott/vous-faites-pas-la-gueule-la.mp3"
    , "kaamelott/vous_la_crachez_votre_pastille.mp3"
    , "kaamelott/vous_laissez_pas_embobiner_ils_cherchent_a_vous_rembobiner.mp3"
    , "kaamelott/vous-me-dites-il-faut-quelque-chose-de-festif.mp3"
    , "kaamelott/vous-me-prenez-vraiment-pour-une-conne.mp3"
    , "kaamelott/vous_nous_utilisez_bon_gre_mal_gre_pour_arriver_sur_la_fin.mp3"
    , "kaamelott/vous-pouvez-aller-vous-gratter.mp3"
    , "kaamelott/vous_rigolez_jespere.mp3"
    , "kaamelott/vous-savez-cest-pas-parce-quun-vieux-moisi.mp3"
    , "kaamelott/vous_voulez_que_je_vous_degage_la_nuque_a_la_serpette.mp3"
    , "kaamelott/vous-vous-devriez-arreter-de-sourire.mp3"
    , "kaamelott/vraiment_impressionnant.mp3"
    , "kaamelott/wooouuuhouhouhou_c_est_mortel.mp3"
    , "kaamelott/ya_pas_de_mal.mp3"
    , "kaamelott/ya_pas_un_pigeon_pour_envoyer_un_message.mp3"
    , "kaamelott/y_en_a_marre_de_se_comporter_comme_des_sagouins.mp3"
    , "kaamelott/zut_la.mp3"

    -- kaamelott sounds autogenerated end
    ]
